const state={products:[],cart:{},acceptingOrders:true,lineAccessToken:null};const $=s=>document.querySelector(s);const money=n=>`NT$ ${Number(n).toLocaleString('zh-TW')}`;const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function initLine(liffId){if(!liffId||typeof liff==='undefined')return;try{await liff.init({liffId});if(liff.isInClient()&&!liff.isLoggedIn()){liff.login();return;}if(liff.isLoggedIn())state.lineAccessToken=liff.getAccessToken();}catch(error){console.error('LINE LIFF 初始化失敗',error);}}
const nativeFetch=window.fetch.bind(window);window.fetch=(input,options={})=>{if(input==='/api/shop/orders'&&state.lineAccessToken){options={...options,headers:{...options.headers,'X-Line-Access-Token':state.lineAccessToken}};}return nativeFetch(input,options);};
async function loadConfig(){try{const response=await fetch('/api/shop/config');if(!response.ok)throw new Error('店家資料載入失敗');const config=await response.json();await initLine(config.liff_id);document.title=`${config.store_name}｜線上點餐`;$('#storeName').textContent=config.store_name;$('#tagline').textContent=config.tagline;$('#storeDescription').textContent=config.description;if(config.hero_image_url)$('#hero').style.backgroundImage=`linear-gradient(90deg,rgba(29,22,19,.82),rgba(29,22,19,.15)),url("${config.hero_image_url.replace(/["\\]/g,'')}")`;state.acceptingOrders=config.accepting_orders!==false;$('#closedNotice').hidden=state.acceptingOrders;const details=[config.phone&&`電話：${config.phone}`,config.address&&`地址：${config.address}`,config.business_hours&&`營業時間：${config.business_hours}`].filter(Boolean);$('#storeInfo').innerHTML=details.map(item=>`<span>${escapeHtml(item)}</span>`).join('');renderProducts();renderCart();}catch(error){console.error(error);}}
async function loadProducts(){try{const response=await fetch('/api/shop/products');if(!response.ok)throw new Error('菜單載入失敗');state.products=await response.json();renderProducts();}catch(error){$('#productList').innerHTML=`<div class="empty">${escapeHtml(error.message)}，請稍後再試。</div>`;}}
function renderProducts(){const list=$('#productList');list.innerHTML=state.products.length?state.products.map(p=>`<article class="product"><img src="${escapeHtml(p.image_url||'https://images.unsplash.com/photo-1547592180-85f173990554?w=600')}" alt="${escapeHtml(p.name)}"><div class="product-info"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'今日新鮮供應')}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-id="${p.id}" aria-label="加入 ${escapeHtml(p.name)}" ${state.acceptingOrders?'':'disabled'}>＋</button></div></div></article>`).join(''):'<div class="empty">目前沒有販售中的商品。</div>';document.querySelectorAll('.add').forEach(b=>b.addEventListener('click',()=>{if(!state.acceptingOrders)return;state.cart[b.dataset.id]=(state.cart[b.dataset.id]||0)+1;renderCart();b.textContent='✓';setTimeout(()=>b.textContent='＋',500);}));}
function cartRows(){return Object.entries(state.cart).map(([id,quantity])=>({product:state.products.find(p=>p.id===id),quantity})).filter(row=>row.product&&row.quantity>0)}
function total(){return cartRows().reduce((sum,row)=>sum+Number(row.product.price)*row.quantity,0)}
function renderCart(){const rows=cartRows();$('#cartCount').textContent=rows.reduce((sum,row)=>sum+row.quantity,0);$('#cartTotal').textContent=money(total());$('#checkoutTotal').textContent=money(total());$('#cartItems').innerHTML=rows.length?rows.map(({product,quantity})=>`<div class="cart-row"><div><strong>${escapeHtml(product.name)}</strong><p>${money(product.price)} × ${quantity}</p></div><div class="quantity"><button data-action="minus" data-id="${product.id}">−</button><b>${quantity}</b><button data-action="plus" data-id="${product.id}">＋</button></div></div>`).join(''):'<div class="empty">購物車還是空的。</div>';$('#startCheckout').disabled=!rows.length||!state.acceptingOrders;document.querySelectorAll('.quantity button').forEach(b=>b.addEventListener('click',()=>{state.cart[b.dataset.id]=(state.cart[b.dataset.id]||0)+(b.dataset.action==='plus'?1:-1);if(state.cart[b.dataset.id]<=0)delete state.cart[b.dataset.id];renderCart();}));}
function toggleCart(open){$('#cartSheet').classList.toggle('open',open);$('#cartSheet').setAttribute('aria-hidden',String(!open));}
$('#openCart').addEventListener('click',()=>toggleCart(true));$('#closeCart').addEventListener('click',()=>toggleCart(false));$('#sheetBackdrop').addEventListener('click',()=>toggleCart(false));$('#startCheckout').addEventListener('click',()=>{toggleCart(false);$('#checkoutDialog').showModal();});$('#closeCheckout').addEventListener('click',()=>$('#checkoutDialog').close());
$('#checkoutForm').addEventListener('submit',async event=>{
  event.preventDefault();const button=$('#submitOrder');
  const body={customer_name:$('#customerName').value,phone:$('#phone').value,fulfillment:document.querySelector('[name="fulfillment"]:checked').value,pickup_time:$('#pickupTime').value,note:$('#note').value,items:cartRows().map(row=>({product_id:row.product.id,quantity:row.quantity}))};
  $('#checkoutError').textContent='';button.disabled=true;button.textContent='送出中…';
  try{
    const response=await fetch('/api/shop/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'送出失敗');
    $('#checkoutDialog').close();$('#successText').textContent=`訂單編號 ${result.id.slice(0,8)}，金額 ${money(result.total)}。`;
    const claimMessage=`確認訂單 ${result.claim_code||''}`;$('#claimBox').hidden=!result.claim_code;$('#claimMessage').textContent=claimMessage;$('#copyClaim').dataset.message=claimMessage;
    $('#lineConfirm').hidden=!result.line_confirm_url;$('#lineConfirm').href=result.line_confirm_url||'#';$('#trackOrder').href=result.tracking_url||'#';
    $('#successDialog').showModal();state.cart={};renderCart();event.target.reset();
  }catch(error){$('#checkoutError').textContent=error.message;}finally{button.disabled=false;button.textContent='送出訂單';}
});
$('#copyClaim').addEventListener('click',async event=>{const text=event.currentTarget.dataset.message||'';try{await navigator.clipboard.writeText(text);}catch{const area=document.createElement('textarea');area.value=text;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();}event.currentTarget.textContent='已複製，請到 LINE 貼上';setTimeout(()=>event.currentTarget.textContent='複製確認訊息',2200);});
$('#finishOrder').addEventListener('click',()=>$('#successDialog').close());Promise.all([loadConfig(),loadProducts()]).then(()=>{renderProducts();renderCart();});
